// Stable identifiers copied from the approved G4 icon board; localized labels are not stored keys.
export const categoryIconIds = [
  'food',
  'coffee',
  'transit',
  'bag',
  'pay',
  'book',
  'timer',
  'activity',
  'heart',
  'leaf',
  'fruit',
  'cake',
  'bottle',
  'noodles',
  'car',
  'bus',
  'bike',
  'plane',
  'fuel',
  'shirt',
  'shoe',
  'gift',
  'phone',
  'cart',
  'home',
  'key',
  'bulb',
  'drop',
  'wifi',
  'tools',
  'pill',
  'clinic',
  'tooth',
  'pet',
  'movie',
  'music',
  'game',
  'coins',
  'bank',
  'card',
  'salary',
  'bonus',
] as const
export type CategoryIconId = (typeof categoryIconIds)[number]
export const categoryIconLabels: Record<CategoryIconId, string> = {
  food: '餐饮',
  coffee: '咖啡',
  transit: '交通',
  bag: '购物',
  pay: '财务',
  book: '阅读',
  timer: '专注',
  activity: '运动',
  heart: '健康',
  leaf: '休闲',
  fruit: '水果',
  cake: '甜点',
  bottle: '饮料',
  noodles: '面食',
  car: '汽车',
  bus: '公交',
  bike: '骑行',
  plane: '机票',
  fuel: '加油',
  shirt: '服饰',
  shoe: '鞋靴',
  gift: '礼物',
  phone: '数码',
  cart: '日用品',
  home: '住房',
  key: '房租',
  bulb: '电费',
  drop: '饮水',
  wifi: '网络',
  tools: '维修',
  pill: '药品',
  clinic: '就医',
  tooth: '牙科',
  pet: '宠物',
  movie: '电影',
  music: '音乐',
  game: '游戏',
  coins: '现金',
  bank: '银行',
  card: '银行卡',
  salary: '工资',
  bonus: '奖励',
}
export const categoryIconGroups: ReadonlyArray<{
  id: string
  label: string
  ids: readonly CategoryIconId[]
}> = [
  {
    id: 'common',
    label: '常用',
    ids: ['food', 'coffee', 'transit', 'bag', 'pay', 'book', 'timer', 'activity', 'heart', 'leaf'],
  },
  { id: 'dining', label: '餐饮', ids: ['food', 'coffee', 'fruit', 'cake', 'bottle', 'noodles'] },
  { id: 'travel', label: '交通出行', ids: ['transit', 'car', 'bus', 'bike', 'plane', 'fuel'] },
  { id: 'shopping', label: '购物消费', ids: ['bag', 'shirt', 'shoe', 'gift', 'phone', 'cart'] },
  { id: 'living', label: '居家缴费', ids: ['home', 'key', 'bulb', 'drop', 'wifi', 'tools'] },
  { id: 'health', label: '健康宠物', ids: ['heart', 'activity', 'pill', 'clinic', 'tooth', 'pet'] },
  { id: 'leisure', label: '学习娱乐', ids: ['book', 'timer', 'leaf', 'movie', 'music', 'game'] },
  { id: 'income', label: '收入财务', ids: ['pay', 'coins', 'bank', 'card', 'salary', 'bonus'] },
]
export const legacyCategoryIconAliases: Record<string, CategoryIconId> = {
  utensils: 'food',
  transport: 'transit',
  shopping: 'bag',
  health: 'heart',
  entertainment: 'movie',
  other: 'bag',
  refund: 'pay',
  work: 'pay',
  study: 'book',
  reading: 'book',
  personal: 'leaf',
  walking: 'activity',
  running: 'activity',
  cycling: 'bike',
  strength: 'activity',
  yoga: 'leaf',
}
export function resolveCategoryIcon(id: string): CategoryIconId {
  return categoryIconIds.includes(id as CategoryIconId)
    ? (id as CategoryIconId)
    : Object.hasOwn(legacyCategoryIconAliases, id)
      ? legacyCategoryIconAliases[id]!
      : 'bag'
}
